---
stages:
  - deploy-to-api-servers
  - lint
  - check
  - generate-access-history
  - deploy

include:
  - project: 'grid5000/grid5000-gitlab-templates'
    ref: master
    file:
      # Execute sonarqube
      - '/sonarqube.yml'
      # Execute rubocop
      - '/rubocop.yml'
      # Import g5k default stages
      - '/g5k-default-stages.yml'

.template-refrepo:
  extends: .template-test
  parallel:
    matrix:
      - DEBIAN_VERSION: [bookworm]
  image: ${CI_REGISTRY}/grid5000/docker/g5k-debian:$DEBIAN_VERSION
  before_script:
    - apt-get update && apt-get -y --no-install-recommends install build-essential wget git ruby ruby-dev bundler rake gpg clustershell graphviz
    # Call the original before_script section
    - !reference [.base, before_script]
    # Add G5K CA certificate
    - wget --no-check-certificate -q https://www.grid5000.fr/certs/ca2019.grid5000.fr.crt -O /usr/local/share/ca-certificates/ca2019.grid5000.fr.crt
    - /usr/sbin/update-ca-certificates

validate-input-data:
  extends: .template-refrepo
  stage: check
  script:
    - bundle exec rake valid:schema
    - bundle exec rake valid:duplicates
    - bundle exec rake valid:required-unwanted-files

wikigen:
  extends: .template-refrepo
  stage: check
  allow_failure: true
  parallel:
    matrix:
      - GENERATOR: [cpu_parameters, disk_reservation, environments, group_storage, hardware, kwollect_metrics, oar_properties, status]
        SITE: global
        DEBIAN_VERSION: [bookworm]
      - GENERATOR: [site_hardware, site_network]
        SITE: [grenoble, lille, luxembourg, lyon, nancy, nantes, rennes, sophia, strasbourg, toulouse]
        DEBIAN_VERSION: [bookworm]
  script:
    - echo "$GRID5000_API" > "${HOME}/.grid5000_api.yml"
    - bundle exec rake gen:wiki NAME=${GENERATOR} SITE=${SITE} DO=diff
  only:
    refs:
      - master

check-no-changes-in-data:
  extends: .template-refrepo
  stage: check
  script:
    - export TZ=Europe/Paris
    - bundle exec rake reference-api
    - git status
    - echo "Checking that git status output is empty..."
    - sh -c '[ "`git status -s`" = "" ]'
    - git diff --exit-code

generate-access-history:
  extends: .template-refrepo
  stage: generate-access-history
  script:
    - export TZ=Europe/Paris
    - bundle exec rake gen:accesses-history
  artifacts:
    paths:
      - data/grid5000/accesses/accesses_mode_history.yaml
    expire_in: 1 week

deploy-to-api-servers:
  stage: deploy-to-api-servers
  tags:
    - grid5000-shell
  script:
    - /srv/ci-runner-scripts/bin/update-api-servers

rebuild_resources_explorer:
  stage: deploy
  # NOTE: this job triggers a rebuild of resources explorer which will be
  # automatically deployed to production if it succeeds, therefore it is only
  # ran on the main branch.
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  trigger:
    project: grid5000/resources-explorer
    # This mirrors the status of RE's pipeline into our own.
    # We may want to revisit this if we want to show a "green" job as soon
    # as the pipeline is triggered, regardless of its status.
    strategy: depend

rspec:
  stage: check  # we use 'checks' here to avoid blocking on this when updating the ref-repo
  extends: .template-refrepo
  script:
    - export TZ=Europe/Paris
    - bundle exec rspec

valid-homogeneity:
  stage: check
  extends: .template-refrepo
  script:
    - bundle exec rake valid:homogeneity
