---
stages:
  - lint
  - validate
  - generate
  - deploy

include:
  - project: 'grid5000/grid5000-gitlab-templates'
    ref: master
    file:
      # Execute sonarqube
      - '/sonarqube.yml'
      # Execute rubocop
      - '/rubocop-rails.yml'
      # Import g5k default stages
      - '/g5k-default-stages.yml'

validate-data:
  extends: .test-for-bullseye
  stage: validate
  script:
    # Add G5K CA certificate
    - wget --no-check-certificate -q https://www.grid5000.fr/certs/ca2019.grid5000.fr.crt -O /usr/local/share/ca-certificates/ca2019.grid5000.fr.crt
    - /usr/sbin/update-ca-certificates
    - bundle exec rake valid:schema
    - bundle exec rake valid:duplicates

wikigen:
  extends: .test-for-bullseye
  stage: validate
  parallel:
    matrix:
      - GENERATOR: [cpu_parameters, disk_reservation, environments, group_storage, hardware, kwollect_metrics, oar_properties, status]
        SITE: global
      - GENERATOR: [site_hardware, site_network]
        SITE: [grenoble, lille, luxembourg, lyon, nancy, nantes, rennes, sophia]
  script:
    - echo "$GRID5000_API" > "${HOME}/.grid5000_api.yml"
    - bundle exec rake gen:wiki NAME=${GENERATOR} SITE=${SITE} DO=diff
  only:
    refs:
      - master

generate-reference-api:
  extends: .test-for-bullseye
  stage: generate
  script:
    - export TZ=Europe/Paris
    - bundle exec rake reference-api
    - git status
    - echo "Checking that git status output is empty..."
    - sh -c '[ "`git status -s`" = "" ]'
    - git diff --exit-code

deploy:
  stage: deploy
  tags:
    - grid5000-shell
  script:
    - /srv/ci-runner-scripts/bin/update-api-servers

rspec:
  stage: deploy  # we use 'deploy' here to avoid blocking on this when updating the ref-repo
  extends: .test-for-bullseye
  script:
    - export TZ=Europe/Paris
    - bundle exec rspec

valid-homogeneity:
  stage: deploy
  extends: .test-for-bullseye
  script:
    - wget --no-check-certificate -q https://www.grid5000.fr/certs/ca2019.grid5000.fr.crt -O /usr/local/share/ca-certificates/ca2019.grid5000.fr.crt
    - /usr/sbin/update-ca-certificates
    - bundle exec rake valid:homogeneity
