---
stages:
  - lint
  - validate
  - generate
  - deploy
  - checks

include:
  - project: 'grid5000/grid5000-gitlab-templates'
    ref: master
    file:
      # Execute sonarqube
      - '/sonarqube.yml'
      # Execute rubocop
      - '/rubocop.yml'
      # Import g5k default stages
      - '/g5k-default-stages.yml'

.template-refrepo:
  extends: .template-test
  parallel:
    matrix:
      - DEBIAN_VERSION: [bookworm]
  image: ${CI_REGISTRY}/grid5000/docker/g5k-debian:$DEBIAN_VERSION
  before_script:
    - apt-get update && apt-get -y --no-install-recommends install build-essential wget git ruby ruby-dev bundler rake gpg clustershell graphviz
    # Call the original before_script section
    - !reference [.base, before_script]
    # Add G5K CA certificate
    - wget --no-check-certificate -q https://www.grid5000.fr/certs/ca2019.grid5000.fr.crt -O /usr/local/share/ca-certificates/ca2019.grid5000.fr.crt
    - /usr/sbin/update-ca-certificates

validate-data:
  extends: .template-refrepo
  stage: validate
  script:
    - bundle exec rake valid:schema
    - bundle exec rake valid:duplicates

wikigen:
  extends: .template-refrepo
  stage: checks
  allow_failure: true
  parallel:
    matrix:
      - GENERATOR: [cpu_parameters, disk_reservation, environments, group_storage, hardware, kwollect_metrics, oar_properties, status]
        SITE: global
        DEBIAN_VERSION: [bookworm]
      - GENERATOR: [site_hardware, site_network]
        SITE: [grenoble, lille, luxembourg, lyon, nancy, nantes, rennes, sophia, strasbourg, toulouse]
        DEBIAN_VERSION: [bookworm]
  script:
    - echo "$GRID5000_API" > "${HOME}/.grid5000_api.yml"
    - bundle exec rake gen:wiki NAME=${GENERATOR} SITE=${SITE} DO=diff
  only:
    refs:
      - master

generate-reference-api:
  extends: .template-refrepo
  stage: generate
  script:
    - export TZ=Europe/Paris
    - bundle exec rake reference-api
    - git status
    - echo "Checking that git status output is empty..."
    - sh -c '[ "`git status -s`" = "" ]'
    - git diff --exit-code

generate-access-history:
  extends: .template-refrepo
  stage: generate
  script:
    - export TZ=Europe/Paris
    - bundle exec rake gen:accesses-history
  artifacts:
    paths:
      - data/grid5000/accesses/accesses_mode_history.yaml
    expire_in: 1 week

deploy:
  stage: deploy
  tags:
    - grid5000-shell
  script:
    - /srv/ci-runner-scripts/bin/update-api-servers

rspec:
  stage: checks  # we use 'checks' here to avoid blocking on this when updating the ref-repo
  extends: .template-refrepo
  script:
    - export TZ=Europe/Paris
    - bundle exec rspec

valid-homogeneity:
  stage: checks
  extends: .template-refrepo
  script:
    - bundle exec rake valid:homogeneity
