#!/usr/bin/ruby -w

require 'yaml'
require 'pp'

Dir['input/grid5000/sites/*/clusters/*/nodes/*.yaml'].each do |f|
  d = YAML::load(IO::read(f))

  # remove bios.configuration
  #d.values.first['bios'].delete('configuration')

  fd = File::new(f, 'w')
  fd.puts("# Generated by g5k-checks (g5k-checks -m api)")
  fd.puts d.to_yaml
  fd.close
end



