all_tasks = [:bindg5k, :conmang5k, :dhcpg5k, :kadeployg5k, :lanpowerg5k]

task :default => all_tasks

all_tasks.each { |t|
desc "Generate #{t} configuration"
task t do
  puts "#{t}.rb -o #{ENV['puppet_repo']} -s #{ENV['sites']}"
  ruby "#{t}.rb -o #{ENV['puppet_repo']} -s #{ENV['sites']}"
end
}
